# Generated by Django 4.2.2 on 2023-06-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenProducePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GreenProduceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GreenProduceProductCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MeatProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MeatProductCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GreenProduceVarietie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('green_produce_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_produce_variety', to='shop.greenproduceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='GreenProduceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=64)),
                ('green_produce_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_produce_unit', to='shop.greenproduceproduct')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='green_produce_price', to='shop.greenproduceprice')),
            ],
        ),
        migrations.CreateModel(
            name='GreenProduceProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('green_produce_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_produce_image', to='shop.greenproduceproduct')),
            ],
        ),
        migrations.AddField(
            model_name='greenproduceproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_produce_category', to='shop.greenproduceproductcategorie'),
        ),
    ]
