# Generated by Django 4.2.2 on 2023-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='unit_abbr',
            field=models.CharField(default='lb', max_length=64),
        ),
    ]
