# Generated by Django 4.2.2 on 2023-06-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeatProduct',
        ),
        migrations.DeleteModel(
            name='MeatProductCategorie',
        ),
    ]
