# Generated by Django 4.2.2 on 2023-09-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productunit_unit_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productgrade')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProductDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.CharField(blank=True, max_length=128, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productdeal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productgrade')),
            ],
        ),
    ]
