# Generated by Django 4.2.2 on 2023-06-27 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_meatproduct_delete_meatproductcategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenproduceunit',
            name='price',
        ),
        migrations.CreateModel(
            name='GreenProduceGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=512)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='green_produce_price', to='shop.greenproduceprice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.greenproduceunit')),
            ],
        ),
    ]
