# Generated by Django 4.2.7 on 2024-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productdeal_relatedproductdealitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgrade',
            name='cost_price',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='productgrade',
            name='cost_price_currency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productgrade',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productgrade',
            name='selling_price',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='productgrade',
            name='selling_price_currency',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
