# Generated by Django 4.2.2 on 2023-08-18 07:55

from django.db import migrations, models
import users.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email_is_validated', models.BooleanField(default=False, verbose_name='email validation status')),
                ('phone_is_validated', models.BooleanField(default=False, verbose_name='phone validation status')),
                ('email_token', models.CharField(default=users.utils.generate_email_verification_token, max_length=6, unique=True)),
                ('email_token_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sms_token', models.CharField(default=users.utils.generate_sms_verification_token, max_length=6, unique=True)),
                ('sms_token_timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_token_is_expired', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='gender')),
                ('ref_code', models.CharField(default=users.utils.generate_ref_code, max_length=12)),
                ('secondary_phone', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='secondary_phone')),
                ('preferred_method', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='preferred_method')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
