# Generated by Django 4.2.5 on 2023-10-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_token_is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
