# Generated by Django 4.2.2 on 2023-08-18 07:55

from django.db import migrations, models
import django.db.models.deletion
import orders.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.SlugField(default=orders.utils.generateID36, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.TextField()),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(max_length=128)),
                ('fulfilment_status', models.CharField(max_length=512)),
                ('payment_status', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=512)),
                ('fulfilment_status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvarietie')),
                ('product_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productgrade')),
            ],
        ),
    ]
