# Generated by Django 4.2.2 on 2023-08-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productunit_unit_abbr'),
        ('orders', '0004_remove_orderitem_product_orderitem_if_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvarietie'),
        ),
    ]
