# Generated by Django 4.2.7 on 2024-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_option_order_delivery_parish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
