# Generated by Django 4.2.7 on 2024-06-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_recurringorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreplacement',
            name='price',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
