# Generated by Django 4.2.2 on 2023-09-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SitePageKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512)),
                ('site_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sitepage')),
            ],
        ),
    ]
