# Generated by Django 4.2.2 on 2023-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default_status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
