# Generated by Django 4.2.2 on 2023-09-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitepage_sitepagekeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepagekeyword',
            name='site_page',
        ),
        migrations.DeleteModel(
            name='SitePage',
        ),
        migrations.DeleteModel(
            name='SitePageKeyword',
        ),
    ]
