# Generated by Django 4.2.2 on 2023-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
