# Generated by Django 4.2.2 on 2023-09-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_userstorecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_step', models.BooleanField(default=False)),
                ('recovery_email', models.EmailField(max_length=254)),
                ('recovery_phone', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
