# Generated by Django 4.2.6 on 2023-11-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_userrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notfication_delivery_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notfification_promotions_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_order_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_prefered_method',
            field=models.CharField(default='Email', max_length=512),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_product_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_diagnostics',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userbusiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
