# Generated by Django 4.2.7 on 2024-06-19 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_usermembership_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='status',
            field=models.CharField(default='Valid', max_length=256),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
